from pathlib import Path

files = {
    'services/task_bank.py': (
        '        ("1 2/5 ÷ 3/10", "14/3", 5, "1 2/5=7/5.", "7/5×10/3=70/15=14/3.", ["division_error"]),\n    ]\n',
        '        ("1 2/5 ÷ 3/10", "14/3", 5, "1 2/5=7/5.", "7/5×10/3=70/15=14/3.", ["division_error"]),\n        ("3/4 ÷ 5/6", "9/10", 5, "Переверни вторую дробь и умножь.", "3/4×6/5=18/20=9/10.", ["division_error"]),\n        ("1 2/3 + 3/5", "34/15", 5, "Приведи дроби к общему знаменателю 15.", "1 2/3=25/15, 3/5=9/15, 25/15+9/15=34/15.", ["wrong_common_denominator", "fraction_addition"]),\n        ("5/8 × 2 1/2", "25/16", 5, "Переведи смешанное число и перемножь дроби.", "2 1/2=5/2, 5/8×5/2=25/16.", ["fraction_multiplication"]),\n        ("(2/3 + 1/4) ÷ 5/6", "11/10", 5, "Сначала сложи дроби, потом умножь на обратную.", "2/3=8/12, 1/4=3/12, 11/12÷5/6=11/12×6/5=66/60=11/10.", ["wrong_common_denominator", "division_error"]),\n    ]\n'
    ),
    'data/arithmetic.json': (
        '  {\n    "id": "arith_h_31",\n    "question": "(48 ÷ 6 + 7) × 5",\n    "answer": "75",\n    "difficulty": 5,\n    "hint": "Сначала действие в скобках.",\n    "explanation": "48 ÷ 6 = 8. Затем 8 + 7 = 15. И наконец 15 × 5 = 75.",\n    "error_patterns": [\n      "order_of_operations"\n    ]\n  },\n  {\n    "id": "arith_h_32",\n    "question": "125 - (18 × 4) + 9",\n    "answer": "62",\n    "difficulty": 5,\n    "hint": "Сначала умножение.",\n    "explanation": "18 × 4 = 72. Далее 125 - 72 = 53. Затем 53 + 9 = 62.",\n    "error_patterns": [\n      "calculation_error"\n    ]\n  }\n]\n',
        '  {\n    "id": "arith_h_31",\n    "question": "(48 ÷ 6 + 7) × 5",\n    "answer": "75",\n    "difficulty": 5,\n    "hint": "Сначала действие в скобках.",\n    "explanation": "48 ÷ 6 = 8. Затем 8 + 7 = 15. И наконец 15 × 5 = 75.",\n    "error_patterns": [\n      "order_of_operations"\n    ]\n  },\n  {\n    "id": "arith_h_32",\n    "question": "125 - (18 × 4) + 9",\n    "answer": "62",\n    "difficulty": 5,\n    "hint": "Сначала умножение.",\n    "explanation": "18 × 4 = 72. Далее 125 - 72 = 53. Затем 53 + 9 = 62.",\n    "error_patterns": [\n      "calculation_error"\n    ]\n  },\n  {\n    "id": "arith_h_33",\n    "question": "18 ÷ (3 × 3)",\n    "answer": "2",\n    "difficulty": 5,\n    "hint": "Сначала умножение в скобках.",\n    "explanation": "3×3=9, 18÷9=2.",\n    "error_patterns": [\n      "order_of_operations"\n    ]\n  },\n  {\n    "id": "arith_h_34",\n    "question": "7 × (5 + 4) - 9",\n    "answer": "54",\n    "difficulty": 5,\n    "hint": "Сначала скобки.",\n    "explanation": "5+4=9, 7×9=63, 63-9=54.",\n    "error_patterns": [\n      "order_of_operations"\n    ]\n  },\n  {\n    "id": "arith_h_35",\n    "question": "12.5 + 3.75",\n    "answer": "16.25",\n    "difficulty": 5,\n    "hint": "Сложи десятичные числа по разрядам.",\n    "explanation": "12.5+3.75=16.25.",\n    "error_patterns": [\n      "decimal_place"\n    ]\n  },\n  {\n    "id": "arith_h_36",\n    "question": "1.25 ÷ 0.5",\n    "answer": "2.5",\n    "difficulty": 5,\n    "hint": "Деление десятичных.",\n    "explanation": "1.25÷0.5=2.5.",\n    "error_patterns": [\n      "decimal_place"\n    ]\n  }\n]\n'
    ),
    'data/word_problems.json': (
        '  {\n    "id": "word_h_31",\n    "question": "В магазине было 120 тетрадей. За день продали 35, а потом привезли ещё 20. Сколько тетрадей стало?",\n    "answer": "105",\n    "difficulty": 5,\n    "hint": "Сначала вычти, потом прибавь.",\n    "explanation": "Было 120. После продажи осталось 120 - 35 = 85. Затем привезли ещё 20: 85 + 20 = 105.",\n    "error_patterns": [\n      "misread_condition"\n    ]\n  },\n  {\n    "id": "word_h_32",\n    "question": "Поезд ехал 3 часа со скоростью 72 км/ч. Какое расстояние он проехал?",\n    "answer": "216",\n    "difficulty": 5,\n    "hint": "Используй формулу расстояния.",\n    "explanation": "Расстояние = скорость × время. 72 × 3 = 216 км.",\n    "error_patterns": [\n      "calculation_error"\n    ]\n  }\n]\n',
        '  {\n    "id": "word_h_31",\n    "question": "В магазине было 120 тетрадей. За день продали 35, а потом привезли ещё 20. Сколько тетрадей стало?",\n    "answer": "105",\n    "difficulty": 5,\n    "hint": "Сначала вычти, потом прибавь.",\n    "explanation": "Было 120. После продажи осталось 120 - 35 = 85. Затем привезли ещё 20: 85 + 20 = 105.",\n    "error_patterns": [\n      "misread_condition"\n    ]\n  },\n  {\n    "id": "word_h_32",\n    "question": "Поезд ехал 3 часа со скоростью 72 км/ч. Какое расстояние он проехал?",\n    "answer": "216",\n    "difficulty": 5,\n    "hint": "Используй формулу расстояния.",\n    "explanation": "Расстояние = скорость × время. 72 × 3 = 216 км.",\n    "error_patterns": [\n      "calculation_error"\n    ]\n  },\n  {\n    "id": "word_h_33",\n    "question": "3/4 кг конфет разделили поровну на 3 человека. Сколько кг получил каждый?",\n    "answer": "1/4",\n    "difficulty": 5,\n    "hint": "Раздели дробь на 3.",\n    "explanation": "3/4 ÷ 3 = 1/4.",\n    "error_patterns": [\n      "division_error",\n      "misread_condition"\n    ]\n  },\n  {\n    "id": "word_h_34",\n    "question": "В саду 20 яблонь, 3/5 дают плоды. Сколько яблонь плодоносят?",\n    "answer": "12",\n    "difficulty": 5,\n    "hint": "20×3/5.",\n    "explanation": "20×3=60, 60/5=12.",\n    "error_patterns": [\n      "fraction_addition",\n      "misread_condition"\n    ]\n  },\n  {\n    "id": "word_h_35",\n    "question": "Книга стоила 240 руб. После скидки 25% её цена стала?",\n    "answer": "180",\n    "difficulty": 5,\n    "hint": "Найди 25% от 240 и вычти.",\n    "explanation": "240×0.25=60, 240-60=180.",\n    "error_patterns": [\n      "calculation_error",\n      "misread_condition"\n    ]\n  },\n  {\n    "id": "word_h_36",\n    "question": "Автомобиль проехал 3/4 пути за 5 ч. Сколько пути он проедет за 1 ч при той же скорости?",\n    "answer": "3/20",\n    "difficulty": 5,\n    "hint": "Раздели пройденную часть на время.",\n    "explanation": "3/4 ÷ 5 = 3/20.",\n    "error_patterns": [\n      "division_error",\n      "unit_conversion"\n    ]\n  }\n]\n'
    )
}

for path, (old, new) in files.items():
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        print(f'NOT FOUND {path}')
        continue
    p.write_text(text.replace(old, new), encoding='utf-8')
    print(f'UPDATED {path}')
